# Generated by Django 6.0.1 on 2026-02-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
