# Generated by Django 6.0.1 on 2026-02-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_mission_about_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='icon_class',
            field=models.CharField(default='fa-user', help_text='FontAwesome class (e.g., fa-user-graduate)', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='use_icon',
            field=models.BooleanField(default=True, help_text='Toggle between using an icon or the uploaded image'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff/'),
        ),
    ]
