# Generated by Django 6.0.2 on 2026-03-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_coursecategory_author_programme_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='syllabus_url',
            field=models.URLField(blank=True, help_text='Link to the official syllabus or resource', null=True),
        ),
    ]
