# Generated by Django 6.0.2 on 2026-03-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_subject_syllabus_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('TEACHING', 'Teaching Staff'), ('NON_TEACHING', 'Non-Teaching Staff')], default='TEACHING', help_text='Categorize staff as teaching or non-teaching', max_length=20),
        ),
    ]
