# Generated by Django 6.0.2 on 2026-03-25 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_staff_staff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_leadership',
            field=models.BooleanField(default=False, help_text='Show in leadership/position-holding sections'),
        ),
        migrations.AddField(
            model_name='staff',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The person this staff member reports to (for organogram structure)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='main.staff'),
        ),
        migrations.AddField(
            model_name='staff',
            name='sort_order',
            field=models.IntegerField(default=10, help_text='Priority in organogram (lower is higher, e.g., 1 for Principal)'),
        ),
    ]
