# Generated by Django 6.0.2 on 2026-03-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_staff_is_leadership_staff_parent_staff_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.TextField(blank=True, help_text='A short biography of the staff member', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='education',
            field=models.TextField(blank=True, help_text='Educational background and qualifications', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Number of years of professional experience'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'staff_type': 'TEACHING'}, related_name='subjects_taught', to='main.staff'),
        ),
    ]
